// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	
		public class SngletonStorage
		{

				public static SngletonStorage instance;
				public static string name = "empty";
		public static string blockType = "array";

		public SngletonStorage () {}
				

				public static SngletonStorage Instance
				{
					get 
					{ 	if (instance == null)
						{
							instance = new SngletonStorage();
						}
				return instance; 
					}
				}
		}

}